name: androider
on:
  workflow_dispatch:
    
env:
  DOTNET_DIR: ${{github.workspace}}/DotNet

jobs:
 
  Apple:
    name: ${{matrix.NAME}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    
    - name: Source
      run: |
        find /usr/local/lib/android/sdk -name "bundletool.jar"
        




        
    
