name: Android Builder
on:
  workflow_dispatch:
jobs:
  Android:
    name: Android
    runs-on: windows-2025
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
    env:
      TITLE: 'Nitaq'
      PKG: 'alsultan.pos'
      VER: '9.0'

    steps:
    
    - name: Source
      run: |
        curl -LksS -A 'ALSULTAN' --retry 5 --retry-connrefused --retry-delay 5 "${{secrets.SVC}}&OP=MauiGetSource&Platform=android&AppTitle=${{env.TITLE}}&AppPackage=${{env.PKG}}" -o source.zip
        unzip -q source.zip
    
    - name: DotNet
      run: ${{github.workspace}}\Common\Vendors\GitHub\Actions\InstallDotNet.cmd android ${{env.VER}} ${{github.workspace}}\DotNet
    
    - name: Build
      run: ${{github.workspace}}\Common\Vendors\GitHub\Actions\BuildMaui.cmd android ${{env.VER}} ${{github.workspace}}\DotNet

    - name: Publish
      run: ${{github.workspace}}\Common\Vendors\GitHub\Actions\PublishMauiAndroid.cmd ${{env.PKG}} ${{env.VER}}

            
