name: androider
run-name: ${{inputs.packages}}

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages"
        required: true
        
env:
  DOTNET_DIR: ${{github.workspace}}\DotNet

concurrency:
 group: ${{github.workflow}}-${{inputs.packages}}
 cancel-in-progress: true

jobs:
     
  Build:
    name: ${{matrix.package}} (${{matrix.format}})
    runs-on: windows-2025
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.Initialize.outputs.includes)}}

    steps:
    - name: Source
      run: |
        for /L %%A in (1,1,20) do (
        	echo Downloading Source Attempt %%A...
        	if not %%A == 1 sleep 10
        	curl -LksS -A 'ALSULTAN' "${{secrets.SVC}}&OP=AndroidGetSource&Package=${{matrix.package}}&AAB=${{matrix.aab}}&DotNetDir=${{env.DOTNET_DIR}}" -o Z && unzip -q Z && goto :eof
        )

    
      
    - name: Google
      run: |
        echo aaa > aaa.aab
        bash ${{github.workspace}}\Common\Vendors\AppStore\Google.sh aaa.aab 'alsultan.hijri2' -1 -1




      
