name: Android Builder
on:
  workflow_dispatch:
jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      TITLE: 'Nitaq'
      PKG: 'alsultan.pos'

    steps:
    
    - name: Source
      run: |
        for i in {1..20}; do
            echo "Downloading Source Attempt ${i}..."
            test $i != 1 && sleep 10
            curl -Lk -A 'ALSULTAN' "${{secrets.SVC}}&OP=MauiGetSource&Platform=android&AppTitle=${{env.TITLE}}&AppPackage=${{env.PKG}}" -o Z || continue
            unzip -q Z && break || continue
        done
        chmod -R 777 Common/Vendors/GitHub/Actions        
    
    - name: DotNet
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/InstallDotNet.sh android ${{github.workspace}}/DotNet
    
    - name: Build
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/BuildMaui.sh android ${{github.workspace}}/DotNet

    - name: Publish
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/PublishMauiAndroid.sh ${{env.PKG}}

            
