name: Maui Builder
run-name: ${{inputs.packages}}

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages"
        required: true
        
env:
  DOTNET_DIR: ${{github.workspace}}/DotNet

concurrency:
 group: ${{github.workflow}}-${{inputs.packages}}
 cancel-in-progress: true

jobs:
    
  Initialize:  
    runs-on: windows-2025
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
    outputs:
      includes: ${{steps.create.outputs.includes}}

    steps:
    - name: Create Builders
      id: create
      run: |
        for /L %%A in (1,1,20) do (
        	echo Downloading Source Attempt %%A...
        	if not %%A == 1 sleep 10
        	curl -LksS -A 'ALSULTAN' "${{secrets.SVC}}&OP=MauiGetSource&Platform=windows&Package=alsultan.net&" -o Z && unzip -q Z && goto :init
        )
        :init
        Common\Vendors\GitHub\Actions\MauiInitialize.cmd ${{inputs.packages}}

  Build:
    needs: Initialize
    name: ${{matrix.package}} (${{matrix.platform}})
    runs-on: ${{matrix.runner}}
    # defaults:
    #   run:
    #     shell: cmd
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.Initialize.outputs.includes)}}

    steps:
    - name: Source
      run: |
        curl -LksS -A 'ALSULTAN' "${{secrets.SVC}}&OP=MauiGetSource&Platform=${{matrix.platform}}&Package=${{matrix.package}}&DotNetDir=${{env.DOTNET_DIR}}" -o Z
        unzip -q Z

    - name: Test
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/a.${{matrix.ext}} android ${{env.DOTNET_DIR}}

