name: Maui Builder
on:
  workflow_dispatch:
    
env:
  TITLE: 'Nitaq'
  PKG: 'alsultan.pos'
  DOTNET_DIR: ${{github.workspace}}\DotNet

jobs:

  Windows:
    name: Windows
    runs-on: windows-2025
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false

    steps:
    
    - name: Source
      run: |
        for /L %%A in (1,1,20) do (
        	echo Downloading Source Attempt %%A...
        	if not %%A == 1 sleep 10
        	curl -LksS -A 'ALSULTAN' "${{secrets.SVC}}&OP=MauiGetSource&Platform=windows&AppTitle=${{env.TITLE}}&AppPackage=${{env.PKG}}&DotNetDir=${{env.DOTNET_DIR}}" -o Z && unzip -q Z && goto :eof
        )
    
    - name: DotNet
      run: ${{github.workspace}}\Common\Vendors\GitHub\Actions\InstallDotNet.cmd windows ${{env.DOTNET_DIR}}
    
    - name: Build
      run: ${{github.workspace}}\Common\Vendors\GitHub\Actions\BuildMaui.cmd windows10.0.19041.0 ${{env.DOTNET_DIR}}

    - name: Upload
      run: ${{github.workspace}}\Common\Vendors\GitHub\Actions\PublishMauiWindows.cmd

  Android:
    name: Android
    runs-on: windows-2025
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false

    steps:
    
    - name: Source
      run: |
        for /L %%A in (1,1,20) do (
        	echo Downloading Source Attempt %%A...
        	if not %%A == 1 sleep 10
        	curl -LksS -A 'ALSULTAN' "${{secrets.SVC}}&OP=MauiGetSource&Platform=android&AppTitle=${{env.TITLE}}&AppPackage=${{env.PKG}}&DotNetDir=${{env.DOTNET_DIR}}" -o Z && unzip -q Z && goto :eof
        )
    
    - name: DotNet
      run: ${{github.workspace}}\Common\Vendors\GitHub\Actions\InstallDotNet.cmd android ${{env.DOTNET_DIR}}
    
    - name: Build
      run: ${{github.workspace}}\Common\Vendors\GitHub\Actions\BuildMaui.cmd android ${{env.DOTNET_DIR}}

    - name: Upload
      run: ${{github.workspace}}\Common\Vendors\GitHub\Actions\PublishMauiAndroid.cmd ${{env.PKG}}

    - name: Publish
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{secrets.AGPA}}
        packageName: ${{env.PKG}}
        releaseFiles: package.aab

  Apple:
    name: ${{matrix.NAME}}
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        include:
    
          - NAME: MacOS
            PLATFORM: macos
            FRAMEWORK: maccatalyst
            PROFILE: NitaqPosMac

          - NAME: iOS
            PLATFORM: ios
            FRAMEWORK: ios
            PROFILE: NitaqPos


    steps:
    
    - name: Source
      run: |
        for i in {1..20}; do
            echo "Downloading Source Attempt ${i}..."
            test $i != 1 && sleep 10
            curl -LksS -A 'ALSULTAN' "${{secrets.SVC}}&OP=MauiGetSource&Platform=${{matrix.PLATFORM}}&AppTitle=${{env.TITLE}}&AppPackage=${{env.PKG}}&SignProfile=${{matrix.PROFILE}}&DotNetDir=${{env.DOTNET_DIR}}" -o Z || continue
            unzip -q Z && break || continue
        done
        chmod -R 777 Common/Vendors/GitHub/Actions
    
    - name: DotNet
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/InstallDotNet.sh ${{matrix.FRAMEWORK}} ${{env.DOTNET_DIR}}
    
    - name: Security
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/AppleCertificates.sh ${{matrix.PLATFORM}} ${{matrix.PROFILE}}

    - name: Build
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/BuildMaui.sh ${{matrix.FRAMEWORK}} ${{env.DOTNET_DIR}}

    - name: Publish
      run: ${{github.workspace}}/Common/Vendors/GitHub/Actions/PublishMauiApple.sh ${{matrix.PLATFORM}}

            
